name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_FRONTEND: bookexchange-frontend
      IMAGE_NAME_BACKEND: bookexchange-backend
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_BACKEND }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_BACKEND }}:${{ env.IMAGE_TAG }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_FRONTEND }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ env.IMAGE_TAG }}
      - name: Update image tags in Kubernetes manifests
        run: |
          sed -i "s|bookexchange-frontend:latest|bookexchange-frontend:${{ github.sha }}|g" k8s/frontend-deployment.yaml
          sed -i "s|bookexchange-backend:latest|bookexchange-backend:${{ github.sha }}|g" k8s/backend-deployment.yaml

      - name: Debug Git Info
        run: |
          git remote -v
          git status
          git log -1

      - name: Push updated manifests
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'mo7thh'
          git config --global user.email 'ymcapone184@gmail.com'
          
          # Set and check remote URL
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          echo "Git remote URL:"
          git remote -v

          # Check current git status before pushing
          git status

          # Check if files are staged
          git diff --cached

          # Try committing if there are changes
          git add ./k8s/*.yaml
          git diff --cached --quiet || git commit -m "Update image tags to ${{ github.sha }}"
          
          # Try pushing
          git push

      
